language: php

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env:
        EXECUTE_CS_CHECK=true
        EXECUTE_COVERAGE=true
  allow_failures:
    - php: nightly

before_install:
  - if [[ $EXECUTE_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - composer self-update

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs --prefer-source --dev

script:
  - mkdir -p build/logs
  - ./vendor/bin/phpunit
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then ./vendor/bin/phpcs ; fi
